const params=new URLSearchParams(location.search),photoNumber=params.get("photo")||"1";
const camera=document.getElementById("camera"),overlay=document.getElementById("overlay"),opacitySlider=document.getElementById("opacity"),resetBtn=document.getElementById("resetBtn"),hideBtn=document.getElementById("hideBtn"),fullscreenBtn=document.getElementById("fullscreenBtn"),startPanel=document.getElementById("startPanel"),startBtn=document.getElementById("startBtn"),controls=document.getElementById("controls"),placeTitle=document.getElementById("placeTitle"),placeDate=document.getElementById("placeDate"),infoBtn=document.getElementById("infoBtn"),infoDialog=document.getElementById("infoDialog"),closeInfoBtn=document.getElementById("closeInfoBtn"),infoTitle=document.getElementById("infoTitle"),infoDate=document.getElementById("infoDate"),infoDescription=document.getElementById("infoDescription"),errorBox=document.getElementById("errorBox");
let state={x:0,y:0,scale:1,rotation:0,opacity:.55},pointers=new Map(),startState={...state},startDistance=0,startAngle=0,startCenter={x:0,y:0};
function showError(m){errorBox.textContent=m;errorBox.style.display="block"}
function applyTransform(){overlay.style.opacity=state.opacity;overlay.style.transform=`translate(calc(-50% + ${state.x}px),calc(-50% + ${state.y}px)) scale(${state.scale}) rotate(${state.rotation}deg)`}
function distance(a,b){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}function angle(a,b){return Math.atan2(b.clientY-a.clientY,b.clientX-a.clientX)*180/Math.PI}function center(a,b){return{x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2}}
async function loadConfig(){let v;try{const r=await fetch("vues.json",{cache:"no-store"});const c=await r.json();v=c[photoNumber]||c["1"]}catch(e){v={titre:`Vue ${photoNumber}`,date:"vers 1900",image:`${photoNumber}.png`,description:"Vue historique de Chorges."}}placeTitle.textContent=v.titre;placeDate.textContent=v.date;infoTitle.textContent=v.titre;infoDate.textContent=v.date;infoDescription.textContent=v.description||"";overlay.src=`images/${v.image||photoNumber+".png"}`}
async function startCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});camera.srcObject=s;startPanel.style.display="none";overlay.style.display="block";controls.style.display="block"}catch(e){showError("Impossible d’ouvrir la caméra. Autorisez la caméra.")}}
overlay.addEventListener("pointerdown",e=>{overlay.setPointerCapture(e.pointerId);pointers.set(e.pointerId,e);startState={...state};const pts=[...pointers.values()];if(pts.length===1)startCenter={x:pts[0].clientX,y:pts[0].clientY};if(pts.length===2){startDistance=distance(pts[0],pts[1]);startAngle=angle(pts[0],pts[1]);startCenter=center(pts[0],pts[1])}});
overlay.addEventListener("pointermove",e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,e);const pts=[...pointers.values()];if(pts.length===1){state.x=startState.x+(pts[0].clientX-startCenter.x);state.y=startState.y+(pts[0].clientY-startCenter.y)}if(pts.length>=2){const d=distance(pts[0],pts[1]),a=angle(pts[0],pts[1]),c=center(pts[0],pts[1]);state.scale=Math.max(.2,Math.min(6,startState.scale*(d/startDistance)));state.rotation=startState.rotation+(a-startAngle);state.x=startState.x+(c.x-startCenter.x);state.y=startState.y+(c.y-startCenter.y)}applyTransform()});
["pointerup","pointercancel","pointerleave"].forEach(n=>overlay.addEventListener(n,e=>{pointers.delete(e.pointerId);if(pointers.size===1){const r=[...pointers.values()][0];startState={...state};startCenter={x:r.clientX,y:r.clientY}}}));
opacitySlider.oninput=e=>{state.opacity=Number(e.target.value);applyTransform()};resetBtn.onclick=()=>{state={x:0,y:0,scale:1,rotation:0,opacity:.55};opacitySlider.value=state.opacity;overlay.classList.remove("hiddenOverlay");hideBtn.textContent="👁";applyTransform()};hideBtn.onclick=()=>{overlay.classList.toggle("hiddenOverlay");hideBtn.textContent=overlay.classList.contains("hiddenOverlay")?"Afficher":"👁"};fullscreenBtn.onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch(e){}};infoBtn.onclick=()=>infoDialog.showModal();closeInfoBtn.onclick=()=>infoDialog.close();startBtn.onclick=startCamera;overlay.onerror=()=>showError(`Image introuvable : ${overlay.src}`);loadConfig().then(applyTransform);